spring.application.name=billing-service
server.port=9130
eureka.client.service-url.defaultZone=http://localhost:9020/eureka/

spring.profiles.active=dev
spring.config.import=optional:configserver:http://localhost:9030

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.root=INFO
logging.level.com.freight.management.billing_service=INFO
