spring.application.name=config-service
server.port=9030
eureka.client.service-url.defaultZone=http://localhost:9020/eureka/

# Native backend search locations (loaded by native profile)
spring.cloud.config.server.native.search-locations=classpath:/configs,file:./configs
