# Native Profile Configuration
# This profile uses the file-based backend instead of Git

spring.cloud.config.server.native.search-locations=classpath:/configs,file:./configs
spring.application.name=config-service
server.port=9030

# Logging
logging.level.org.springframework.cloud.config.server=DEBUG
logging.level.org.springframework.cloud.bootstrap=DEBUG
